require: rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

AllCops:
  NewCops: enable
